name: hackaton
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  mapbox_gl: ^0.16.0
  flutter_html: ^2.2.1
  camera: ^0.10.3+2
  material_design_icons_flutter: ^6.0.7096
  geolocator: ^9.0.2
  confetti: ^0.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true